method: s_supermask
name: b60
save_path: results/mnist/s_supermask/weights
save: Yes
load: Yes
optimizer: configs/optimizers/sgd_vgg11.yaml
trainer: configs/training/mnist.yaml
device: 0
method_parameters:
  prune_percentage: 0.60
  global_pruning: No
  mask_epochs: 10
  binary_mask: Yes
  supermask:
    name: weights
    initialization:
      name: uniform
      low: -5
      high: 5



